APP_NAME: lovatacopy
SHORT_PROJECT_NAME: lovatacopy
APP_KEY: 'base64:GflFIbxu6fStW/P/7dPW74qMWqRiAfyC+bCjsLPBjkY='
APP_LOCALE: en
LOG_CHANNEL: daily
FILESYSTEM_DRIVER: local
ACTIVE_THEME: lovata

DATABASE_TYPE: mysql
DB_CONNECTION: mysql

NODE_VERSION: 18
MYSQL_VERSION: '8.0'
PGSQL_VERSION: 15
MARIADB_VERSION: 11.1.2

APP_CODE_PATH_CONTAINER: /var/www/html
