#!/usr/bin/env bash

set -e

role=${CONTAINER_ROLE:-app}

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ "$role" = "app" ]; then
    if [ $# -gt 0 ];then
        exec gosu $WWWUSER "$@"
    else
        exec php-fpm
    fi
elif [ "$role" = "queue" ]; then
    echo "Running the queue..."
    gosu $WWWUSER php /var/www/html/artisan queue:work --verbose --tries=3 --timeout=90
elif [ "$role" = "scheduler" ]; then
    while [ true ]
    do
        gosu $WWWUSER php /var/www/html/artisan schedule:run --verbose --no-interaction & sleep 60
    done
fi
