REDIS_HOST: redis
REDIS_PASSWORD: null
REDIS_PORT: 6379

MAIL_MAILER: smtp
MAIL_HOST: mailhog
MAIL_PORT: 1025
MAIL_USERNAME: null
MAIL_PASSWORD: null
MAIL_ENCRYPTION: null
MAIL_FROM_ADDRESS: noreplay@project.loc
MAIL_FROM_NAME: "${APP_NAME}"
