- name: 'Update project'
  hosts: localhost
  tasks:
      -   include_tasks: project/init-vars.yml
      -   include_tasks: project/env.yml
      -   include_tasks: project/domain-configuration.yml
      -   include_tasks: octobercms/october-license.yml
