- name: 'Update project'
  hosts: localhost
  tasks:
      -   include_tasks: project/init-vars.yml
      -   include_tasks: octobercms/october-license.yml
      -   include_tasks: project/composer-update.yml
      -   include_tasks: octobercms/october-install.yml
